//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaracteristicasHospedaje
    {
        public int idCaracteristicaHospedaje { get; set; }
        public Nullable<int> idLugarHospedaje { get; set; }
        public Nullable<int> idCaracteristica { get; set; }
    
        public virtual Caracteristica Caracteristica { get; set; }
        public virtual LugarHospedaje LugarHospedaje { get; set; }
    }
}
