//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caracteristica
    {
        public Caracteristica()
        {
            this.CaracteristicasHospedaje = new HashSet<CaracteristicasHospedaje>();
        }
    
        public int idCaracteristica { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idCategoriaCaracteristicas { get; set; }
        public Nullable<int> idTipoCaracteristica { get; set; }
    
        public virtual CategoriaCaracteristicas CategoriaCaracteristicas { get; set; }
        public virtual TipoCaracteristica TipoCaracteristica { get; set; }
        public virtual ICollection<CaracteristicasHospedaje> CaracteristicasHospedaje { get; set; }
    }
}
