//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasaDptoOCabana
    {
        public CasaDptoOCabana()
        {
            this.Disponibilidad = new HashSet<Disponibilidad>();
        }
    
        public int idCasaDptoOCabana { get; set; }
        public string nombreCasaDptoOCabana { get; set; }
        public Nullable<int> idLugarHospedaje { get; set; }
        public Nullable<int> cantidadHabitaciones { get; set; }
        public Nullable<int> cantidadAmbientes { get; set; }
        public Nullable<int> cantidadBanios { get; set; }
        public Nullable<int> idComplejo { get; set; }
        public Nullable<int> capacidadMaxima { get; set; }
    
        public virtual Complejo Complejo { get; set; }
        public virtual LugarHospedaje LugarHospedaje { get; set; }
        public virtual ICollection<Disponibilidad> Disponibilidad { get; set; }
    }
}
