//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complejo
    {
        public Complejo()
        {
            this.CasaDptoOCabana = new HashSet<CasaDptoOCabana>();
        }
    
        public int idComplejo { get; set; }
        public Nullable<int> idTipoComplejo { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idLugarHospedaje { get; set; }
    
        public virtual ICollection<CasaDptoOCabana> CasaDptoOCabana { get; set; }
        public virtual CategoriaHospedaje CategoriaHospedaje { get; set; }
        public virtual LugarHospedaje LugarHospedaje { get; set; }
        public virtual TipoComplejo TipoComplejo { get; set; }
    }
}
