//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilidad
    {
        public int idDisponibilidad { get; set; }
        public Nullable<System.DateTime> fechaDesde { get; set; }
        public Nullable<System.DateTime> fechaHasta { get; set; }
        public Nullable<int> idHabitacion { get; set; }
        public Nullable<int> idCasaODpto { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        public virtual CasaDptoOCabana CasaDptoOCabana { get; set; }
        public virtual EstadoReserva EstadoReserva { get; set; }
        public virtual Habitacion Habitacion { get; set; }
    }
}
