//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio
    {
        public Domicilio()
        {
            this.Persona = new HashSet<Persona>();
            this.Sucursal = new HashSet<Sucursal>();
        }
    
        public int idDomicilio { get; set; }
        public string calle { get; set; }
        public Nullable<int> numero { get; set; }
        public string dpto { get; set; }
        public string barrio { get; set; }
        public Nullable<int> idLocalidad { get; set; }
    
        public virtual Localidad Localidad { get; set; }
        public virtual ICollection<Persona> Persona { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
    }
}
