//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoTramite
    {
        public EstadoTramite()
        {
            this.Tramite = new HashSet<Tramite>();
        }
    
        public int idEstadoTramite { get; set; }
        public string nombreEstadoTramite { get; set; }
    
        public virtual ICollection<Tramite> Tramite { get; set; }
    }
}
