//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LugarHospedaje
    {
        public LugarHospedaje()
        {
            this.CaracteristicasHospedaje = new HashSet<CaracteristicasHospedaje>();
            this.CasaDptoOCabana = new HashSet<CasaDptoOCabana>();
            this.Complejo = new HashSet<Complejo>();
            this.Hotel = new HashSet<Hotel>();
        }
    
        public int idLugarHospedaje { get; set; }
        public Nullable<int> idNegocio { get; set; }
        public Nullable<int> idTipoLugarHospedaje { get; set; }
        public Nullable<bool> moduloReservas { get; set; }
    
        public virtual ICollection<CaracteristicasHospedaje> CaracteristicasHospedaje { get; set; }
        public virtual ICollection<CasaDptoOCabana> CasaDptoOCabana { get; set; }
        public virtual ICollection<Complejo> Complejo { get; set; }
        public virtual ICollection<Hotel> Hotel { get; set; }
        public virtual Negocio Negocio { get; set; }
        public virtual TipoLugarHospedaje TipoLugarHospedaje { get; set; }
    }
}
