//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio
    {
        public Negocio()
        {
            this.Comercio = new HashSet<Comercio>();
            this.FotosNegocio = new HashSet<FotosNegocio>();
            this.LugarHospedaje = new HashSet<LugarHospedaje>();
            this.Negocio1 = new HashSet<Negocio>();
            this.Solicitud = new HashSet<Solicitud>();
            this.Sucursal = new HashSet<Sucursal>();
            this.Tramite = new HashSet<Tramite>();
        }
    
        public int idNegocio { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<int> idTipoNegocio { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<bool> estaAprobado { get; set; }
        public Nullable<int> idNegocioModif { get; set; }
    
        public virtual ICollection<Comercio> Comercio { get; set; }
        public virtual ICollection<FotosNegocio> FotosNegocio { get; set; }
        public virtual ICollection<LugarHospedaje> LugarHospedaje { get; set; }
        public virtual ICollection<Negocio> Negocio1 { get; set; }
        public virtual Negocio Negocio2 { get; set; }
        public virtual TipoDeNegocio TipoDeNegocio { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Solicitud> Solicitud { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
        public virtual ICollection<Tramite> Tramite { get; set; }
    }
}
