//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaginasXPerfil
    {
        public int idPaginaXPerfil { get; set; }
        public int idPerfil { get; set; }
        public int idPagina { get; set; }
    
        public virtual Paginas Paginas { get; set; }
        public virtual Perfiles Perfiles { get; set; }
    }
}
