//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paginas
    {
        public Paginas()
        {
            this.PaginasXPerfil = new HashSet<PaginasXPerfil>();
        }
    
        public int idPagina { get; set; }
        public string nombrePagina { get; set; }
        public string controlador { get; set; }
        public string vista { get; set; }
    
        public virtual ICollection<PaginasXPerfil> PaginasXPerfil { get; set; }
    }
}
