//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfiles
    {
        public Perfiles()
        {
            this.PaginasXPerfil = new HashSet<PaginasXPerfil>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int idPerfil { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<PaginasXPerfil> PaginasXPerfil { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
