//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int idPersona { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string email { get; set; }
        public Nullable<int> documento { get; set; }
        public Nullable<int> idSexo { get; set; }
        public Nullable<int> idTelefono { get; set; }
        public Nullable<int> idTipoDocumento { get; set; }
        public Nullable<int> idDomicilio { get; set; }
    
        public virtual Domicilio Domicilio { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual Telefono Telefono { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
