//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public Provincia()
        {
            this.Localidad = new HashSet<Localidad>();
        }
    
        public int idProvincia { get; set; }
        public string nombreProvincia { get; set; }
        public Nullable<int> idPais { get; set; }
    
        public virtual ICollection<Localidad> Localidad { get; set; }
        public virtual Pais Pais { get; set; }
    }
}
