//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubro
    {
        public Rubro()
        {
            this.Comercio = new HashSet<Comercio>();
        }
    
        public int idRubro { get; set; }
        public string nombreRubro { get; set; }
    
        public virtual ICollection<Comercio> Comercio { get; set; }
    }
}
