//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int idSolicitud { get; set; }
        public Nullable<int> idUsuarioSolicitante { get; set; }
        public Nullable<System.DateTime> fechaDesde { get; set; }
        public Nullable<System.DateTime> fechaHasta { get; set; }
        public Nullable<int> cantidadPersonas { get; set; }
        public Nullable<int> cantidadLugares { get; set; }
        public string observacion { get; set; }
        public Nullable<int> idNegocio { get; set; }
    
        public virtual Negocio Negocio { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
