//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public Telefono()
        {
            this.Persona = new HashSet<Persona>();
        }
    
        public int idTelefono { get; set; }
        public string movil { get; set; }
        public string fijo { get; set; }
        public string alternativo { get; set; }
    
        public virtual ICollection<Persona> Persona { get; set; }
    }
}
