//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoLugarHospedaje
    {
        public TipoLugarHospedaje()
        {
            this.LugarHospedaje = new HashSet<LugarHospedaje>();
        }
    
        public int idTipoLugarHospedaje { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<LugarHospedaje> LugarHospedaje { get; set; }
    }
}
