//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tramite
    {
        public int idTramite { get; set; }
        public Nullable<int> idEstadoTramite { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<int> idUsuarioSolicitante { get; set; }
        public Nullable<int> idUsuarioResponsable { get; set; }
        public Nullable<int> idTipoTramite { get; set; }
        public Nullable<int> idNegocio { get; set; }
        public string comentario { get; set; }
    
        public virtual EstadoTramite EstadoTramite { get; set; }
        public virtual Negocio Negocio { get; set; }
        public virtual TipoTramite TipoTramite { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
