//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.FotosUsuario = new HashSet<FotosUsuario>();
            this.Negocio = new HashSet<Negocio>();
            this.Solicitud = new HashSet<Solicitud>();
            this.Tramite = new HashSet<Tramite>();
            this.Tramite1 = new HashSet<Tramite>();
        }
    
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string password { get; set; }
        public Nullable<int> idPerfil { get; set; }
        public Nullable<int> idPersona { get; set; }
    
        public virtual ICollection<FotosUsuario> FotosUsuario { get; set; }
        public virtual ICollection<Negocio> Negocio { get; set; }
        public virtual Perfiles Perfiles { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Solicitud> Solicitud { get; set; }
        public virtual ICollection<Tramite> Tramite { get; set; }
        public virtual ICollection<Tramite> Tramite1 { get; set; }
    }
}
